export type BreedSeed = {
  name: string;
  origin: string;
  temperament: string;
  lifeSpan: string;
};

export const breedSeeds: BreedSeed[] = [
  { name: "アビシニアン", origin: "エチオピア", temperament: "活発, 好奇心旺盛, 社交的", lifeSpan: "9 - 15" },
  { name: "アメリカンボブテイル", origin: "アメリカ", temperament: "知的, 人懐っこい, 遊び好き", lifeSpan: "11 - 15" },
  { name: "アメリカンカール", origin: "アメリカ", temperament: "愛情深い, 好奇心旺盛, 穏やか", lifeSpan: "12 - 16" },
  { name: "アメリカンショートヘア", origin: "アメリカ", temperament: "穏やか, 社交的, 適応力が高い", lifeSpan: "13 - 17" },
  { name: "アメリカンワイヤーヘア", origin: "アメリカ", temperament: "穏やか, 遊び好き, 愛情深い", lifeSpan: "10 - 14" },
  { name: "バリニーズ", origin: "アメリカ", temperament: "社交的, おしゃべり, 知的", lifeSpan: "12 - 18" },
  { name: "ベンガル", origin: "アメリカ", temperament: "活発, エネルギッシュ, 好奇心旺盛", lifeSpan: "12 - 16" },
  { name: "バーマン", origin: "ミャンマー", temperament: "穏やか, 愛情深い, 社交的", lifeSpan: "12 - 16" },
  { name: "ボンベイ", origin: "アメリカ", temperament: "愛情深い, 遊び好き, 人懐っこい", lifeSpan: "12 - 16" },
  { name: "ブリティッシュショートヘア", origin: "イギリス", temperament: "穏やか, マイペース, 落ち着いている", lifeSpan: "12 - 17" },
  { name: "バーミーズ", origin: "ミャンマー", temperament: "社交的, 愛情深い, 遊び好き", lifeSpan: "10 - 16" },
  { name: "シャルトリュー", origin: "フランス", temperament: "落ち着いている, 忠実, 静か", lifeSpan: "12 - 15" },
  { name: "コーニッシュレックス", origin: "イギリス", temperament: "活発, 遊び好き, 好奇心旺盛", lifeSpan: "12 - 16" },
  { name: "デボンレックス", origin: "イギリス", temperament: "遊び好き, 愛情深い, いたずら好き", lifeSpan: "9 - 15" },
  { name: "エジプシャンマウ", origin: "エジプト", temperament: "活発, 忠実, 少し臆病", lifeSpan: "12 - 15" },
  { name: "エキゾチックショートヘア", origin: "アメリカ", temperament: "穏やか, 愛情深い, マイペース", lifeSpan: "12 - 15" },
  { name: "ハバナブラウン", origin: "イギリス", temperament: "好奇心旺盛, 愛情深い, 社交的", lifeSpan: "10 - 15" },
  { name: "ヒマラヤン", origin: "アメリカ", temperament: "穏やか, 静か, 愛情深い", lifeSpan: "9 - 15" },
  { name: "ジャパニーズボブテイル", origin: "日本", temperament: "活発, 社交的, 知的", lifeSpan: "9 - 15" },
  { name: "コラット", origin: "タイ", temperament: "忠実, 愛情深い, 慎重", lifeSpan: "10 - 15" },
  { name: "ラパーム", origin: "アメリカ", temperament: "愛情深い, 穏やか, 遊び好き", lifeSpan: "10 - 15" },
  { name: "メインクーン", origin: "アメリカ", temperament: "穏やか, フレンドリー, 賢い", lifeSpan: "12 - 15" },
  { name: "マンクス", origin: "マン島", temperament: "遊び好き, 忠実, 社交的", lifeSpan: "8 - 14" },
  { name: "マンチカン", origin: "アメリカ", temperament: "活発, 社交的, 好奇心旺盛", lifeSpan: "12 - 15" },
  { name: "ノルウェージャンフォレストキャット", origin: "ノルウェー", temperament: "穏やか, 独立心が強い, 愛情深い", lifeSpan: "14 - 16" },
  { name: "オシキャット", origin: "アメリカ", temperament: "活発, 社交的, 遊び好き", lifeSpan: "10 - 15" },
  { name: "オリエンタルショートヘア", origin: "イギリス", temperament: "社交的, おしゃべり, エネルギッシュ", lifeSpan: "10 - 15" },
  { name: "ペルシャ", origin: "イラン", temperament: "穏やか, 静か, 愛情深い", lifeSpan: "10 - 17" },
  { name: "ピクシーボブ", origin: "アメリカ", temperament: "愛情深い, 忠実, 穏やか", lifeSpan: "13 - 16" },
  { name: "ラグドール", origin: "アメリカ", temperament: "穏やか, 愛情深い, リラックス", lifeSpan: "12 - 17" },
  { name: "ロシアンブルー", origin: "ロシア", temperament: "物静か, 上品, 少し内気", lifeSpan: "10 - 20" },
  { name: "サバンナ", origin: "アメリカ", temperament: "活発, 好奇心旺盛, エネルギッシュ", lifeSpan: "12 - 20" },
  { name: "スコティッシュフォールド", origin: "イギリス", temperament: "穏やか, 愛情深い, 順応性が高い", lifeSpan: "11 - 14" },
  { name: "セルカークレックス", origin: "アメリカ", temperament: "穏やか, 忍耐強い, 愛情深い", lifeSpan: "10 - 15" },
  { name: "シャム", origin: "タイ", temperament: "社交的, おしゃべり, 知的", lifeSpan: "12 - 20" },
  { name: "シベリアン", origin: "ロシア", temperament: "愛情深い, 活発, 忠実", lifeSpan: "12 - 15" },
  { name: "シンガプーラ", origin: "シンガポール", temperament: "活発, 好奇心旺盛, 愛情深い", lifeSpan: "11 - 15" },
  { name: "スノーシュー", origin: "アメリカ", temperament: "社交的, 愛情深い, 知的", lifeSpan: "12 - 15" },
  { name: "ソマリ", origin: "アメリカ", temperament: "活発, 好奇心旺盛, 遊び好き", lifeSpan: "12 - 16" },
  { name: "スフィンクス", origin: "カナダ", temperament: "愛情深い, エネルギッシュ, 社交的", lifeSpan: "8 - 14" },
  { name: "トンキニーズ", origin: "カナダ", temperament: "社交的, 遊び好き, 愛情深い", lifeSpan: "12 - 16" },
  { name: "トイガー", origin: "アメリカ", temperament: "活発, 知的, 社交的", lifeSpan: "12 - 15" },
  { name: "トルコアンゴラ", origin: "トルコ", temperament: "活発, 知的, 愛情深い", lifeSpan: "12 - 18" },
  { name: "ターキッシュバン", origin: "トルコ", temperament: "活発, 独立心が強い, 水遊び好き", lifeSpan: "12 - 17" },
  { name: "ミックス", origin: "-", temperament: "個体差が大きい", lifeSpan: "12 - 18" },
];
